### ISSUE TITLE
Cannot install with panda

### ISSUE THREAD

**Issue by ugjka** [zoffixznet/perl6-IRC-Client-Plugin-HNY#1]
`[ugjka@ChakraPC ~]$ panda install IRC::Client::Plugin::HNY
resolve stage failed for IRC::Client::Plugin::HNY: Dependency IRC::Client:ver<2.001001>:auth<Zoffix Znet> is not present in the module ecosystem
  in method get-deps at /home/ugjka/.perl6/sources/582CB7486602954A4601BDCE5A0EAC54B05DA58A (Panda) line 209
  in method resolve at /home/ugjka/.perl6/sources/582CB7486602954A4601BDCE5A0EAC54B05DA58A (Panda) line 252
  in sub MAIN at /home/ugjka/.perl6/resources/E0D978079BB5081DE986D058BB8AB08252F05CC8 line 20
  in block <unit> at /home/ugjka/.perl6/resources/E0D978079BB5081DE986D058BB8AB08252F05CC8 line 165
## Failure Summary

IRC::Client::Plugin::HNY(
        *resolve stage failed for IRC::Client::Plugin::HNY: Dependency IRC::Client:ver<2.001001>:auth<Zoffix Znet> is not present in the module ecosystem)
`

**Comment by zoffixznet** [comment]
This module needs updating to new API of IRC::Client

**Comment by ugjka** [comment]
There's still 3 Months of time to do that :P

**Comment by ugjka** [comment]
Ok, I figured it out. Learned a bit about perl6 lol. I'll compare notes when you update the script

**Comment by zoffixznet** [comment]
> when you update the script

FWIW, that likely won't happen until a couple of weeks before the New Years. Fixing bugs in my New Years bots has become a tradition of mine :joy_cat:

**Comment by zoffixznet** [comment]
Fixed in 53d603f
