### ISSUE TITLE
timezone google api

### ISSUE THREAD

**Issue by ugjka** [zoffixznet/perl6-IRC-Client-Plugin-HNY#3]
This is what I use for my own bot ( https://github.com/ugjka/newyearsbot )

https://stackoverflow.com/a/14988400

**Comment by ugjka** [comment]
Btw I loved your bot before I learned golang, I wrote my own now, happy 2018

**Comment by ugjka** [comment]
shame we had great time at #freenode-newyears

**Comment by zoffixznet** [comment]
I hanged around for a bit... I think I'm too old to enjoy a bunch of nerds talking shit to each other :P

Saw your bot. It worked good.

**Comment by ugjka** [comment]
Thanks!
